export const SET_USERDATA_INIT = 'SET_USERDATA_INIT'
export const SET_USERDATA = 'SET_USERDATA'
export const SET_CURRNETLOCATIONWEATHER = 'SET_CURRNETLOCATIONWEATHER'
export const SET_REALLOCATIONCOORDINATE = 'SET_REALLOCATIONCOORDINATE'
export const REMOVE_USERDATA = 'REMOVE_USERDATA'

